### ISSUE TITLE
Input type "file" shouldn't have a "form-control" class

### ISSUE THREAD

**Issue by thomaslhostis** [adrianhurt/play-bootstrap3#36]
Hi everyone,

There's only one example of an input type file in the Bootstrap documentation, and it does not have a "form-control" class. And this class is not applied to radios, checkboxes, nor selects. So it's easy to bypass this by setting the b3.file class to "", like this:

    @b3.file(form("file"), 'class -> "")

Would it be right to just not apply this class to this type of input?

**Comment by adrianhurt** [comment]
I agree with you. It's changed from new 0.4.5-P2X-SNAPSHOT version

Thanks!

**Comment by mkurz** [comment]
@adrianhurt 
Just a suggestion: Could you please use a own commit for changes like this? Because now you put the changes suggested by thomaslhostis into the "0.4.5-P24-SNAPSHOT" commit, which makes it hard to track changes of the project. I think the "0.4.5-P24-SNAPSHOT" should just contain the changes to the `build.sbt` etc. but the change here should be it's own commit. Also this makes it much more easier to revert a change/commit.
Thanks!

**Comment by adrianhurt** [comment]
Ok, you're right. I'll try to do these things better :) In any case, everything relevant is documented within the [changelog page](http://play-bootstrap3.herokuapp.com/changelog)

**Comment by mkurz** [comment]
Thanks

**Comment by mkurz** [comment]
@adrianhurt One more thing: The changelog on http://play-bootstrap3.herokuapp.com/ (the first page) is not update to date.

**Comment by adrianhurt** [comment]
Yes, I prefer not to put the Snapshots into the first page, because they're in development. Specially when the changes from the last version are not very relevant.

**Comment by mkurz** [comment]
OK - makes sense :smile:

**Comment by adrianhurt** [comment]
Thanks. It's great to know the library it's useful for more people than me! :smile:

**Comment by mkurz** [comment]
It sure is :+1:
