### ISSUE TITLE
Reduce input size without impacting the div that contains it

### ISSUE THREAD

**Issue by thomaslhostis** [adrianhurt/play-bootstrap3#37]
Hi again,

This is not an issue. As the title says, I want to limit the size of an input in a horizontal form, without reducing the size of the div that contains it, because it can contain help blocks that shouldn't be cut in width.

See:
![screen shot 2015-08-04 at 18 50 52](https://cloud.githubusercontent.com/assets/4296630/9066857/3b908828-3ada-11e5-8279-119380023de1.png)

As you can see in this screen shot, the "CP" (zip code) field is smaller than the other ones. And because of this, the size of the error message is limited to the width of the field.

I got round this by setting a fixed size to the input:

    	@b3.text(form("zipCode"), '_label -> "CP *", 'style -> "width:130px !important")

But it wouldn't work if I wanted it to use a "col-xx-xx" class to define its size, because of the "form-control" class which sets the width to 100%.

Does anyone has run into this one?

**Comment by adrianhurt** [comment]
Hi @thomaslhostis. If you want to resize only the input you could do one of this possibilities:

* Use style as you did, but it's not the more elegant way.
```
@b3.text(form("zipCode"), '_label -> "CP *", 'style -> "width:130px !important")
```
* Use a custom class and set its width in your css.
```
@b3.text(form("zipCode"), 'class -> "input-small form-control", '_label -> "CP *")
```
If any of them satisfy your requirements, then the problem is that the default horizontal one described in Bootstrap 3 doesn't fits you. In this case, check the [Extend it!](http://play-bootstrap3.herokuapp.com/extend-it) section, because you can:
* Create your own text helper using `b3.inputWrapped` to include a new row and col wrapping the input:
```
@b3.my.text(form("zipCode"), colWidth = "col-md-6", '_label -> "CP *")
```
With a `b3/my/text.scala.html` file with the code like this:
```
@(field: play.api.data.Field, colWidth: String, args: (Symbol,Any)*)(implicit handler: b3.B3FieldConstructor, messages: Messages)
@b3.inputWrapped("text", field, args:_*) { input =>
  <div class="row">
    <div class="@colWidth">
      @input
    </div>
  </div>
}
```

* Create your own custom field constructor that fits your requirements.

**Comment by thomaslhostis** [comment]
Creating a custom field constructor will do perfectly fine. I was kind of hoping there was a quicker way to do it as it is a small requirement. But the library is great, so it's quite straightforward.

Thanks mate
